{% set name = "elektronn2" %}
{% set version = "0.6.0" %}
{% set sha256 = "6777f929bdae9101abc25da9518dd47ca13edd975ae57768aa199e1a4fe8b7e0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-v{{ version }}.tar.gz
  url: https://pypi.org/packages/source/e/{{ name }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [not linux64 or py37]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python <3.7
    - setuptools

  run:
    - python <3.7
    - theano <0.10
    - numpy
    - scipy
    - matplotlib
    - scikit-learn
    - scikit-image
    - h5py
    - future
    - tqdm
    - numba
    - colorlog
    - pydotplus
    - seaborn
    - prompt_toolkit <2
    - jedi
    - psutil
    - ipython

test:
  imports:
    - elektronn2
    - elektronn2.data
    - elektronn2.neuromancer
    - elektronn2.training
    - elektronn2.utils
  commands:
    - elektronn2-train --help

about:
  home: http://elektronn2.readthedocs.io/en/latest/elektronn2.html
  license: GPLv3
  license_file: LICENSE.txt
  summary: 'A highly configurable toolkit for training 3d/2d CNNs and general Neural Networks'
  doc_url: http://elektronn2.readthedocs.io/en/latest/
  dev_url: https://github.com/ELEKTRONN/ELEKTRONN2

extra:
  recipe-maintainers:
    - mdraw
