travis:
  secure:
    BINSTAR_TOKEN: TgVlBKVVs95c63cN/dFbYSeiIQGCUG3N6MUNsqn5Zk27cnrcw6+dyABAXtMDInx+vSJrvMJOTqhnLpYC9Qr1S3JjqGdlqtmO3gTYJAXvYm+v9ZotWZ+S9ndAfmAFznAiY9dG6Arb2LVSwas2MKd9gvYRZ8evr6XeVPv6WORdhZNf6OTuvzJ0ayUwSY6687lEC+152PYhKOZrRlcSSzjcNEYAkwVKyT3dpqXUo23VzwwIxzJ+ob3XjOiPliW9lMZVCexsXIYJQdZsthq0JY82s66dgJmov2cyAYVATW6VG2w9QCWoiF6Xj+DwvzIul2+rO/8C7TjomCB4cuHQv3mzSz7CuqohGvkwsKOv9vYHwJS845dMLsgbKBhAOoyk0YgpCKMUFY8OcUQtOw21uk11IExTTD2AiYCW2Jsxo7VzkFjiEQz0/FnzFgLXFEhL/xNaZfIE8OhL7/h+jpZK3Z5WmfP68hDo+x87mOaf50yeKDjQkb1sI8JyRfsfZDv/0g/DMmgvH6JXvcL6gCi9ZvmaDOeik5LIU9KxAGiqMrMiPUpv2FFdwoI+FNlNymTa1k8c45xiVyxh6sAP6YLBgeEqlnPBoiHLX3ci6bDxxBNOxkc772yBztaUFMlRdx1LGZjx4WzCoYF56z0iBE5sIuoyf3FQQeXprZ2z4FQbVHHjtqc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
