travis:
  secure:
    BINSTAR_TOKEN: XQaMc3HDrniGp028Se2Xj2D6p6E65AERa5AK7LZUuYbOqsqX/GricJGbyqiu6JVNB02o2DWOyOMubUjD+a9vYrUvihNnntGTmrmGEHYoLyABmiB48v4gwywo3FSOTRDi1ya6/RQ62//HiuA9dL8AEQhVEMC10sEkzdaAslhMDKrFnb2XPEBRP3SQub+YC6oqTuioe+ui8I2TlJmG7fHlgVW4csKFXa7XbzzCSzj8kzGCb3bGKmSbzA896umNxVsfO9UfRSz+BrRzgHHd7axAAakjlyRXQCJTYo6GaAZf8GfRgwPQ1KwDSxGMFgGvCf/X3fpqN90r3AAA30LETCjN0MJqo3SokNckszifNKkz/wuZDw0fYpBTg1bywMRR1fBfHBoLlE9AAhU71+4Zxepp7iTCm07Iess0DF2fbo0QOF1z62IRq8XuP9qGhnoQP0ELs3IR+o8dRLy4skgUwpMkRyn3BYxYS6wV/JxHw1SNtZjF8+JvvmNjmvXADpU8Hrk76p8s2UjbhriS1xN+PsNUlplKMZliks/RVqe28tmPptiGTd9da6otMKwzpF7y7fNz8q9MQPxk6QqWCV3kPiWR/tZ1bYf5ETyW4G/Q7fRePklOjCBHnwyoWpl/mEs3Euun99aVwpK8UZZMPLMQw7+27IEbTGJuPwcz2FIh3GseJc4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
