travis:
  secure:
    BINSTAR_TOKEN: B38IHpTXYsggH7vGXjUT6ZQ8+pnwXqKNLVnG8HaMcgtHEJaNbDnJTOswnRtDVm9MUJQY6NG83LoQqzCrozmNLq+bnsZrOICVSfjLGd0IZbiwp7lG1BU3xI7DuUjT6AOgDiSx8fc4Gu/Vdc8wYFPlFyByCpHRmlN37RWKbpJkCAi5owMaHty+ry68RwIqR3uPUw35Ksjb3ofaporxgFzdR8jWFB8HNlVEh7nRlyvm8JhLMuNvEBu5tlScJdi4TCgDkneOE0wdBadNiXKDh5QZvgxzaPky7LKnREU+J8TvqZ4q+6SwLkHXl1Twtq5rlZbUQf5aaMxHeW4hpUEYNKzbc/R3QbHrvPVGDzCrhaYRNq/VIojCpiTmHZVPZsfjiKLB82Up3UQSZehLwOHaTcALAyTHnxqGhrwKeuSSliPm47MGMSgvBaQ6CjlYxtRt4teJ2yqBZLzeqt2+5TldZlBqX7SdWg+BVyOoSfaaegrMETXZTUv4806xVVJgLlJt9m86iv8GfXTETiq199QSwT61MK1EzLYGtfVNcPxFYxJf4fnaJFdNLZnRJKWI+p38NjJUlWzZLfukyqZVCvCyD2BeIeToDoOH6M5Fj+Zw7bivs/GFyKO0MvM+Iy2P5IU0WtG0J6v+jfHIeJNkZQxpljmY9PPc/D9uHmkLfFTDxmycV08=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
